### ISSUE TITLE
Exception field not defined in documents for scalar functions

### ISSUE THREAD

**Issue by emkornfield** [substrait-io/substrait#14]
[The scalar function yaml file](https://github.com/substrait-io/substrait/blob/main/extensions/scalar_functions.yaml) has an exception field, which isn't mentioned in [scalar function definition](https://substrait.io/expressions/scalar_functions/)

**Comment by jacques-n** [comment]
Oops. That was in an older version of the spec. Missed removing from the yaml file. It became clear that there is no reason for structured information about exceptions to be included in the function signatures since it's really an internal concern of a functions semantics. Mind posting a patch to remove from the yaml file?
