### ISSUE TITLE
Implement `approx_count_distinct` via options to `count`

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait#313]
`approx_count_distinct` was  implemented as its own separate function in `extensions/functions_aggregate_approx.yaml` in #204. This is inconsistent with more recent PRs that have implemented `approx_` variants via options:
- #278 
- #279
- #311

For consistency, we should implement the approximate distinct count via options to `count` instead of as its own separate function, and we should delete the file `extensions/functions_aggregate_approx.yaml`.

**Comment by jvanstraten** [comment]
Hm... I'm not sure how to feel about this, because I don't think this generalizes to a sensible "count_approx" variant? Or does it? If not, I feel like it might make more sense to add an `AGGREGATION_INVOCATION_APPROX_DISTINCT` enum variant to protobuf. I can't say I know any, but I could at least imagine algorithms that not just count approximately-distinct items but also return them for further processing.

**Comment by jvanstraten** [comment]
Okay, in that case I'm fine with this change.

**Comment by jacques-n** [comment]
I think I'm -1 on this change. 

Distinct is an aggregate level concept that influences the handling of an arbitrary function. Distinct is something that can be applied to any aggregate function, not just count. It means that the input of the function is different, (it is not a property of the function). 

There is no "count distinct" function. There is a count function that counts a distinct input. There is an approximate count distinct function that does an approximation of the distinct values before counting (and thus is not something that uses distinct). As such, I don't think this patterns similar to the other functions.

I'm not aware of a real world use of `AGGREGATION_INVOCATION_APPROX_DISTINCT`, primarily since the algorithms that people use to approximate distinct typically don't hold individual values.

**Comment by westonpace** [comment]
Given that `count_distinct` has been removed I think this issue is no longer valid.  Feel free to reopen if I am misunderstanding things.
