### ISSUE TITLE
Question about ReferenceRel

### ISSUE THREAD

**Issue by eedalong** [substrait-io/substrait#476]
Hi guys, I am really confused about this ReferenceRel. 
1. It is defined in `AggregateFunction`?
![image](https://user-images.githubusercontent.com/39682259/226503132-ef8798b1-b237-4934-981f-ca1702d68400.png)

2. How we suppose to decide the subtree_ordinal for one operator to make it referencable by other Rels?

**Comment by westonpace** [comment]
The `ReferenceRel` message, as it is currently implemented, is incomplete and ambiguous.  There was an attempt to clarify things in https://github.com/substrait-io/substrait/pull/288 but that did not merge.  However, there is still some good discussion and I recommend you check it out.

Someone should either finish what #288 started or they should remove `ReferenceRel`.  I believe this has been low priority since no one is using it or has needed it yet.

**Comment by westonpace** [comment]
I will attempt to answer your questions:

> It is defined in AggregateFunction?

Yes, that is wrong.  It should be a top-level message in algebra.proto.

> How we suppose to decide the subtree_ordinal for one operator to make it referencable by other Rels?

The `subtree_ordinal` here is an index into `Plan::relations`:

```
message Plan {
  ...
  // one or more relation trees that are associated with this plan.
  repeated PlanRel relations = 3;
```

So if the `subtree_ordinal` is `2` then it is the third item in `Plan::relations`.

**Comment by jacques-n** [comment]
ReferenceRel is now complete and available for use.
