### ISSUE TITLE
Question: why does ReadRel include a schema?

### ISSUE THREAD

**Issue by bkietz** [substrait-io/substrait#51]
It's not clear to me why ReadRel includes the base schema of the table to be read. That seems like something the producer would configure in a catalog and that the consumer would look up in the same catalog.

**Comment by bkietz** [comment]
I don't understand why plan manipulation requires access to the input and output schemas, could you give an example? For example, to me it seems possible to consolidate adjacent Project relations into a single Project, or to extract a filter expression and push it into a Read relation.

If you mean that someone outside the consumer is for example validating argument types to a call to the "+" function then that doesn't make sense to me since the producer is responsible for providing the return type of all functions. Why would the producer ever specify a type expression for the return type of "+" if the type of the inputs was also specified by the producer? To me, the ability to specify a return type expression implies that the producer can specify addition with `+(alpha, beta)` and accommodate potentially evolved types of the fields `alpha` and `beta` with a custom promotion scheme. In any case the flow of responsibility for declaring schemas isn't clear to me and I'd love to hammer out what interaction between a producer, consumer, and catalog is intended to be.

> 1. Catalog retrieval is typically a relatively expensive operation

Fair, but how else can a producer or a consumer become aware of tables and their schemas? It seems to me that this communication still needs to take place, even if it is cached or known ahead of time or something

> 2. Re-retrieving data can result in consistency issues

Even storing the schema alongside each read table doesn't guarantee that a consumer can identify invalidated IR. As a trivial example, it would be possible to update which table the field `foreign_key:int`references. This would invalidate a plan which joins on that field to the old table without changing any schemas.

It seems more reasonable to me to defer validation of IR as out-of-scope for the IR itself since some consumers *do* support strong versioning and would probably prefer to rely on that instead of using a Schema as a checksum. At the least, could we make this schema optional so that such producer/consumers don't need to pay for an unused field? [Required is forever, etc](https://developers.google.com/protocol-buffers/docs/proto#specifying_field_rules)

> 3. ... previously available.

Baking the schema into produced IR sounds like an optimization, so again I'd say it should be optional at least since consumers may have their own ideas about how to optimize interaction with a catalog and may prefer not to rely on the producer to send the schema.

**Comment by jacques-n** [comment]
> Required is forever...

I think there is mixing here between the serialized representation and the required semantics. The schema idl is declared in protobuf3 format. The protobuf team was so passionate about required being a bad idea that in protobuf3 required does not exist. All fields are either optional or repeated. Not specifying a behavior is implicitly is optional. That being said, this field is declared required in the specification for now. In the future, we may change how we serialize the schema concept so optional makes for serialization even though the specification requires it.

> how else can a producer or a consumer become aware of tables and their schemas? It seems to me that this communication still needs to take place, even if it is cached or known ahead of time or something

While there are simple cases where catalog retrieval is a single step, there are also a lot of cases where catalog retrieval is a multistep process where some may be done in a FE and some may be done in a BE. For example, let's use Iceberg table using Glue metastore backing (many others are pretty similar). The process is roughy:

1. Retrieve metadata from the Glue metastore. Typically schema and a path to a metadata file. 
1. Retrieve the metadata file which produces a set of manifest list files. 
1. Retrieve each manifest list and get a list manifests, 
1. Retrieve each manifest and get a list of files, filtering files that don't fit predicates
1. Retrieve each file (let's say Parquet) and produce actual data.

Different systems may subdivide this work in different ways (which parts are done in the FE). In this world, it is highly likely that a consumer would only be able to do a subset of this work. For example, a consumer may only be capable of doing the last two of the 5 steps listed here. Assuming that the consumer duplicates catalog work only really makes sense in the simplest cases.

> It seems more reasonable to me to defer validation of IR as out-of-scope for the IR itself

Whether plan validation is a first class concern of the IR is mostly beside the point from my pov. My first goal is to ensure completeness. So your thoughts really bring up two questions where we may have different perspectives:

1. Should type information be explicit in a plan?
1. Should it be possible to insert an intermediary in the plan pipeline to, for example, optimize the plan and know it is producing an updated plan without having to consult an external system (e.g. catalog)? 

From my POV, both of these are yes. For 1: Type information is a key part of the understanding of what a plan is trying to express. For 2: A hope of Substrait is to decompose generalized plan processing (move away from monolisthic databases). If the plan is incomplete, it makes it quite difficult to introduce "plan microservices" if you will (in the same way that Arrow Flight communicates schema in all cases, even if both systems might have previously known the schema of data).

I think there is a separate question which you may also be asking: Should a ReadRel object simply express the output schema rather than internal concerns (e.g. determine derived schema using combination of original schema and projection). This is a question I considered when writing up the initial representation. My primary thinking was that projection is almost universally supported in reading of data from a source and thus including it makes sense. That being said, an alternative would be to simply express the output schema of a scan and any projection information to be an internal concern of a specific type of read. I'm fine with either.

> Baking the schema into produced IR sounds like an optimization
I think of it as the opposite. To build a valid plan, one must have had the type information. Removing this type information at the point of serialization is work and drastically reduces the ability to manipulate/validate the plan without external context. The only reason I can see to remove that schema information is to reduce size--which feels like an optimization that reduces the completeness of the plan.
